import React, {useState} from 'react'
import {useNavigate } from 'react-router-dom'
import react from '../assets/react.svg'
import {getRandomPrompt} from '../utils'
import {FormField, Loader} from '../Components'
const CreatePost = () => {
   const navigate = useNavigate()
   const [form, setForm] = useState({
    name:'',
    prompt:'',
    photo:''
   })
   const [generating, setGenerating] = useState(false)
   const [loading, setLoading] = useState(false)

   const handleSubmit=(e)=>{

   }

   const handleChange=(e)=>{
    setForm((prev)=>{
      return {...prev, [e.target.name]:e.target.value}
    })
   }

   const handleSurpriseMe=()=>{
    const prompt = getRandomPrompt(form.prompt) 
    setForm({...form, prompt:prompt})
   }
   const generateImage=async()=>{
    if(form.prompt){
      try{
        setGenerating(true);
        const resp = await fetch('http://localhost:4000/api/v1/dalle',{
          method:'POST',
          headers:{
            'Content-Type':'application/json',
          },
          body:JSON.stringify({prompt:form.prompt})
        })
        const data =await resp.json();
        console.log(data)
        setForm({...form, photo:data.photo})
      }catch(err){
        console.log(err)
        alert(err)
      }finally{
        setGenerating(false)
      }
    }else{
      alert('Please enter the prompt')
      setGenerating(false)
    }
    
   }
   return (
    <section className='max-w-7xl mx-auto'>
      <div>
        <h1 className='font-extrabold text-black text-[32px]'>Create</h1>
        <p className='mt-2 text-[#666e75] text-[14px] max-w-[500px]'>Create a collection of Visually stunning images generated by AI</p>
      </div>
      <form className='mt-16 max-w-3xl' onSubmit={handleSubmit}>
        <div className='flex flex-col gap-5'>
          <FormField 
            labelName="Your Name" 
            type="text" 
            name='name'
            placeholder="type your name here" 
            value={form.name}
            handleChange={handleChange}
            />
          <FormField 
            labelName="Prompt" 
            type="text" 
            name="prompt" 
            placeholder="add your prompt" 
            value={form.prompt}
            handleChange={handleChange}
            isSurpriseMe={handleSurpriseMe}
            />
            <div className='border-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-50 w-64 p-3 h-64 flex justify-center items-center'>
              {form.photo ? (
                <img src={form.photo} alt={form.prompt} className='w-full h-full object-contain' />
              ):(
                <img src={react} alt='preview' className='w-9/12 h-9/12 object-contain opacity-40' />
              )}

              {generating && (
                <div className='absolute inset-0 z-0 flex justify-center items-center rounded'>
                  <Loader/>
                </div>
              )}
            </div>
        </div>
        <div className='mt-5 flex gap-5'>
              <button type="button" onClick={generateImage} 
                className='text-white bg-green-700 font-medium rounded-md text-sm w-full sm:w-auto px-5 py-2.5 text-center'>
                {generating ? 'Generating...': 'Generate'}
              </button>
        </div>

        <div>
          <p className='mt-2 text-[#666e75] text-[14px]' >Once you have created image you can share it</p>
          <button type="submit" className='mt-3 text-white bg-[#6469ff] font-medium rounded-md text-sm w-full sm:w-auto px-5 py-2. text-center'>
            {loading ? 'Sharing...': 'Share'}
          </button>
          </div>
      
      </form>
    </section>
  )
}

export default CreatePost