import React, {useState, useEffect} from 'react'
import {Loader, Card, FormField} from 'react'
import RenderCards from './RenderCards'

// const RenderCards = ({data, title})=>{
//   if(data?.length > 0) 
//     return data.map((post)=><Card key={post._id} {...post}/>)
//   return (
//     <h2 className='mt-5 font-bold text-[#6449ff] text-xl uppercase'>
//       {title}
//     </h2>
//   )
// }


const Home = () => {
  const [loading, setLoading] = useState(false)
  const [allPosts, setAllPosts] = useState(null)
  const [searchText, setsearchText] = useState('')

  const handleChange=()=>{

  }
  const handleSurpriseMe = ()=>{}
  return (
    <section>
      <div>
        <h1 className='font-extrabold text-black text-[32px]'>The Community showcase</h1>
        <p className='mt-2 text-[#666e75] text-[14px] max-w-[500px]'>Browse through a collection of Visually stunning images generated by AI</p>
      </div>
      <div className='mt-16' >
        <input className='bg-grey-50 border-grey-300 text-grey-900 text-sm rounded-lg 
        focus:ring-[#4649ff] focus:border-[#4649ff] outline-none block w-full p-3'
        name="searchText" value={searchText} labelName="search" placeholder="search here" type="text" handleChange={handleChange} isSurpriseMe={handleSurpriseMe}/>
      </div>
      <div className='mt-10'>
        {
          loading ? (
            <div className='flex justify-center items-center'>
              <Loader/>
            </div>)
          :
          <React.Fragment>
            {searchText && (
              <h2 className='font-medium text-[#666e75] text-ml mb-3'>
                Showing results for <span className='text-[#222328]'>{searchText}</span>
              </h2>
            )}
            <div className='grid lg:grid-cols-4 xs:grid-cols-2 sm:grid-cols-3 grid-cols-1 gap-3'>
              {searchText ? 
                <RenderCards data={[]} title="No search results found"/> : 
                <RenderCards data={[]} title="No Posts found"/>
              }
            </div>
          </React.Fragment>
        }
      </div>
    </section>
  )
}

export default Home